# sts_feetech_driver_params.yaml
sts_feetech_driver:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baudrate: 1000000

    joint_names:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll
      # - gripper   # при необходимости

    joint_shoulder_pan.id: 1
    joint_shoulder_pan.angle_min: -1.91986
    joint_shoulder_pan.angle_max: 1.91986
    joint_shoulder_pan.raw_min: 0
    joint_shoulder_pan.raw_max: 4095

    joint_shoulder_lift.id: 2
    joint_shoulder_lift.angle_min: -1.74533
    joint_shoulder_lift.angle_max: 1.74533
    joint_shoulder_lift.raw_min: 0
    joint_shoulder_lift.raw_max: 4095

    joint_elbow_flex.id: 3
    joint_elbow_flex.angle_min: -1.74533
    joint_elbow_flex.angle_max: 1.5708
    joint_elbow_flex.raw_min: 0
    joint_elbow_flex.raw_max: 4095

    joint_wrist_flex.id: 4
    joint_wrist_flex.angle_min: -1.65806
    joint_wrist_flex.angle_max: 1.65806
    joint_wrist_flex.raw_min: 0
    joint_wrist_flex.raw_max: 4095

    joint_wrist_roll.id: 5
    joint_wrist_roll.angle_min: -2.79253
    joint_wrist_roll.angle_max: 2.79253
    joint_wrist_roll.raw_min: 0
    joint_wrist_roll.raw_max: 4095

    # joint_gripper.id: 6
    # joint_gripper.angle_min: -0.174533
    # joint_gripper.angle_max: 1.74533
    # joint_gripper.raw_min: 0
    # joint_gripper.raw_max: 4095