SO101 Hardware Interface: SMS_STS Class Reference
SMS_STS Class Reference
#include <SMS_STS.h>
Public Member Functions
SMS_STS ()
SMS_STS (u8 End)
SMS_STS (u8 End, u8 Level)
virtual int WritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC=0)
virtual int RegWritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC=0)
virtual void SyncWritePosEx (u8 ID[], u8 IDN, s16 Position[], u16 Speed[], u8 ACC[])
virtual int Mode (u8 ID, u8 mode)
virtual int WriteSpe (u8 ID, s16 Speed, u8 ACC=0)
virtual int RegWriteSpe (u8 ID, s16 Speed, u8 ACC=0)
virtual void SyncWriteSpe (u8 ID[], u8 IDN, s16 Speed[], u8 ACC[])
virtual int WritePwm (u8 ID, s16 Pwm)
virtual int RegWritePwm (u8 ID, s16 Pwm)
virtual void SyncWritePwm (u8 ID[], u8 IDN, s16 Pwm[])
virtual int EnableTorque (u8 ID, u8 Enable)
virtual int unLockEprom (u8 ID)
virtual int LockEprom (u8 ID)
virtual int CalibrationOfs (u8 ID)
virtual int FeedBack (int ID)
virtual int ReadPos (int ID)
virtual int ReadSpeed (int ID)
virtual int ReadLoad (int ID)
virtual int ReadVoltage (int ID)
virtual int ReadTemper (int ID)
virtual int ReadMove (int ID)
virtual int ReadCurrent (int ID)
Public Member Functions inherited from SCSerial
SCSerial ()
SCSerial (u8 End)
SCSerial (u8 End, u8 Level)
virtual int getErr ()
virtual int setBaudRate (int baudRate)
virtual bool begin (int baudRate, const char *serialPort)
virtual void end ()
Public Member Functions inherited from SCS
SCS ()
SCS (u8 End)
SCS (u8 End, u8 Level)
int genWrite (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen)
int regWrite (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen)
int RegWriteAction (u8 ID=0xfe)
void syncWrite (u8 ID[], u8 IDN, u8 MemAddr, u8 *nDat, u8 nLen)
int writeByte (u8 ID, u8 MemAddr, u8 bDat)
int writeWord (u8 ID, u8 MemAddr, u16 wDat)
int Read (u8 ID, u8 MemAddr, u8 *nData, u8 nLen)
int readByte (u8 ID, u8 MemAddr)
int readWord (u8 ID, u8 MemAddr)
int Ping (u8 ID)
int syncReadPacketTx (u8 ID[], u8 IDN, u8 MemAddr, u8 nLen)
int syncReadPacketRx (u8 ID, u8 *nDat)
int syncReadRxPacketToByte ()
int syncReadRxPacketToWrod (u8 negBit=0)
void syncReadBegin (u8 IDN, u8 rxLen)
void syncReadEnd ()
Private Attributes
u8 Mem [SMS_STS_PRESENT_CURRENT_H-SMS_STS_PRESENT_POSITION_L+1]
Additional Inherited Members
Public Attributes inherited from SCSerial
unsigned long int IOTimeOut
int Err
Public Attributes inherited from SCS
u8 Level
u8 End
u8 Error
u8 syncReadRxPacketIndex
u8 syncReadRxPacketLen
u8 * syncReadRxPacket
u8 * syncReadRxBuff
u16 syncReadRxBuffLen
u16 syncReadRxBuffMax
Protected Member Functions inherited from SCSerial
int writeSCS (unsigned char *nDat, int nLen)
int readSCS (unsigned char *nDat, int nLen)
int writeSCS (unsigned char bDat)
void rFlushSCS ()
void wFlushSCS ()
Protected Member Functions inherited from SCS
void writeBuf (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen, u8 Fun)
void Host2SCS (u8 *DataL, u8 *DataH, u16 Data)
u16 SCS2Host (u8 DataL, u8 DataH)
int Ack (u8 ID)
Protected Attributes inherited from SCSerial
int fd
struct termios orgopt
struct termios curopt
unsigned char txBuf [255]
int txBufLen
Constructor & Destructor Documentation
SMS_STS() [1/3]
SMS_STS::SMS_STS ()
References SCS::End.
SMS_STS() [2/3]
SMS_STS::SMS_STS (u8 End)
SMS_STS() [3/3]
SMS_STS::SMS_STS (u8 End, u8 Level)
Member Function Documentation
CalibrationOfs()
int SMS_STS::CalibrationOfs (u8 ID) virtual
References SMS_STS_TORQUE_ENABLE, and SCS::writeByte().
EnableTorque()
int SMS_STS::EnableTorque (u8 ID, u8 Enable) virtual
References SMS_STS_TORQUE_ENABLE, and SCS::writeByte().
FeedBack()
int SMS_STS::FeedBack (int ID) virtual
References SCSerial::Err, Mem, SCS::Read(), and SMS_STS_PRESENT_POSITION_L.
LockEprom()
int SMS_STS::LockEprom (u8 ID) virtual
References SMS_STS_LOCK, and SCS::writeByte().
Mode()
int SMS_STS::Mode (u8 ID, u8 mode) virtual
References SCSerial::Err, SMS_STS_MODE, and SCS::writeByte().
ReadCurrent()
int SMS_STS::ReadCurrent (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMS_STS_PRESENT_CURRENT_H, SMS_STS_PRESENT_CURRENT_L, and SMS_STS_PRESENT_POSITION_L.
ReadLoad()
int SMS_STS::ReadLoad (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMS_STS_PRESENT_LOAD_H, SMS_STS_PRESENT_LOAD_L, and SMS_STS_PRESENT_POSITION_L.
ReadMove()
int SMS_STS::ReadMove (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SMS_STS_MOVING, and SMS_STS_PRESENT_POSITION_L.
ReadPos()
int SMS_STS::ReadPos (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMS_STS_PRESENT_POSITION_H, and SMS_STS_PRESENT_POSITION_L.
ReadSpeed()
int SMS_STS::ReadSpeed (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMS_STS_PRESENT_POSITION_L, SMS_STS_PRESENT_SPEED_H, and SMS_STS_PRESENT_SPEED_L.
ReadTemper()
int SMS_STS::ReadTemper (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SMS_STS_PRESENT_POSITION_L, and SMS_STS_PRESENT_TEMPERATURE.
ReadVoltage()
int SMS_STS::ReadVoltage (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SMS_STS_PRESENT_POSITION_L, and SMS_STS_PRESENT_VOLTAGE.
RegWritePosEx()
int SMS_STS::RegWritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC = 0) virtual
References SCS::Host2SCS(), SCS::regWrite(), and SMS_STS_ACC.
RegWritePwm()
int SMS_STS::RegWritePwm (u8 ID, s16 Pwm) virtual
References SCS::Host2SCS(), SCS::regWrite(), and SMS_STS_GOAL_TIME_L.
RegWriteSpe()
int SMS_STS::RegWriteSpe (u8 ID, s16 Speed, u8 ACC = 0) virtual
References SCS::Host2SCS(), SCS::regWrite(), SMS_STS_ACC, and SMS_STS_GOAL_SPEED_L.
SyncWritePosEx()
void SMS_STS::SyncWritePosEx (u8 ID[], u8 IDN, s16 Position[], u16 Speed[], u8 ACC[]) virtual
References SCS::Host2SCS(), SMS_STS_ACC, and SCS::syncWrite().
SyncWritePwm()
void SMS_STS::SyncWritePwm (u8 ID[], u8 IDN, s16 Pwm[]) virtual
References SCS::Host2SCS(), SMS_STS_GOAL_TIME_L, and SCS::syncWrite().
SyncWriteSpe()
void SMS_STS::SyncWriteSpe (u8 ID[], u8 IDN, s16 Speed[], u8 ACC[]) virtual
References SCS::genWrite(), SCS::Host2SCS(), SMS_STS_ACC, SMS_STS_GOAL_SPEED_L, and SCS::syncWrite().
unLockEprom()
int SMS_STS::unLockEprom (u8 ID) virtual
References SMS_STS_LOCK, and SCS::writeByte().
WritePosEx()
int SMS_STS::WritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC = 0) virtual
References SCS::genWrite(), SCS::Host2SCS(), and SMS_STS_ACC.
WritePwm()
int SMS_STS::WritePwm (u8 ID, s16 Pwm) virtual
References SCS::genWrite(), SCS::Host2SCS(), and SMS_STS_GOAL_TIME_L.
WriteSpe()
int SMS_STS::WriteSpe (u8 ID, s16 Speed, u8 ACC = 0) virtual
References SCS::genWrite(), SCS::Host2SCS(), SMS_STS_ACC, and SMS_STS_GOAL_SPEED_L.
Member Data Documentation
Mem
u8 SMS_STS::Mem[SMS_STS_PRESENT_CURRENT_H-SMS_STS_PRESENT_POSITION_L+1] private
Referenced by FeedBack(), ReadCurrent(), ReadLoad(), ReadMove(), ReadPos(), ReadSpeed(), ReadTemper(), and ReadVoltage().
The documentation for this class was generated from the following files:
scservo_sdk/SMS_STS.h
scservo_sdk/SMS_STS.cpp