SO101 Hardware Interface: SCS Class Reference
SCS Class Reference abstract
#include <SCS.h>
Public Member Functions
SCS ()
SCS (u8 End)
SCS (u8 End, u8 Level)
int genWrite (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen)
int regWrite (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen)
int RegWriteAction (u8 ID=0xfe)
void syncWrite (u8 ID[], u8 IDN, u8 MemAddr, u8 *nDat, u8 nLen)
int writeByte (u8 ID, u8 MemAddr, u8 bDat)
int writeWord (u8 ID, u8 MemAddr, u16 wDat)
int Read (u8 ID, u8 MemAddr, u8 *nData, u8 nLen)
int readByte (u8 ID, u8 MemAddr)
int readWord (u8 ID, u8 MemAddr)
int Ping (u8 ID)
int syncReadPacketTx (u8 ID[], u8 IDN, u8 MemAddr, u8 nLen)
int syncReadPacketRx (u8 ID, u8 *nDat)
int syncReadRxPacketToByte ()
int syncReadRxPacketToWrod (u8 negBit=0)
void syncReadBegin (u8 IDN, u8 rxLen)
void syncReadEnd ()
Public Attributes
u8 Level
u8 End
u8 Error
u8 syncReadRxPacketIndex
u8 syncReadRxPacketLen
u8 * syncReadRxPacket
u8 * syncReadRxBuff
u16 syncReadRxBuffLen
u16 syncReadRxBuffMax
Protected Member Functions
virtual int writeSCS (unsigned char *nDat, int nLen)=0
virtual int readSCS (unsigned char *nDat, int nLen)=0
virtual int writeSCS (unsigned char bDat)=0
virtual void rFlushSCS ()=0
virtual void wFlushSCS ()=0
void writeBuf (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen, u8 Fun)
void Host2SCS (u8 *DataL, u8 *DataH, u16 Data)
u16 SCS2Host (u8 DataL, u8 DataH)
int Ack (u8 ID)
Constructor & Destructor Documentation
SCS() [1/3]
SCS::SCS ()
References Error, and Level.
SCS() [2/3]
SCS::SCS (u8 End)
References End, Error, and Level.
SCS() [3/3]
SCS::SCS (u8 End, u8 Level)
References End, Error, and Level.
Member Function Documentation
Ack()
int SCS::Ack (u8 ID) protected
References Error, Level, and readSCS().
Referenced by genWrite(), regWrite(), RegWriteAction(), writeByte(), and writeWord().
genWrite()
int SCS::genWrite (u8 ID, u8 MemAddr, u8 * nDat, u8 nLen)
References Ack(), INST_WRITE, rFlushSCS(), wFlushSCS(), and writeBuf().
Referenced by SCSCL::PWMMode(), SMS_STS::SyncWriteSpe(), SCSCL::WritePos(), SMS_STS::WritePosEx(), SMSBL::WritePosEx(), SMSCL::WritePosEx(), SMS_STS::WritePwm(), SCSCL::WritePWM(), SMS_STS::WriteSpe(), SMSBL::WriteSpe(), and SMSCL::WriteSpe().
Host2SCS()
void SCS::Host2SCS (u8 * DataL, u8 * DataH, u16 Data) protected
References End.
Referenced by SCSCL::RegWritePos(), SMS_STS::RegWritePosEx(), SMSBL::RegWritePosEx(), SMSCL::RegWritePosEx(), SMS_STS::RegWritePwm(), SMS_STS::RegWriteSpe(), SCSCL::SyncWritePos(), SMS_STS::SyncWritePosEx(), SMSBL::SyncWritePosEx(), SMSCL::SyncWritePosEx(), SMS_STS::SyncWritePwm(), SMS_STS::SyncWriteSpe(), SCSCL::WritePos(), SMS_STS::WritePosEx(), SMSBL::WritePosEx(), SMSCL::WritePosEx(), SMS_STS::WritePwm(), SCSCL::WritePWM(), SMS_STS::WriteSpe(), SMSBL::WriteSpe(), SMSCL::WriteSpe(), and writeWord().
Ping()
int SCS::Ping (u8 ID)
References Error, INST_PING, readSCS(), rFlushSCS(), wFlushSCS(), and writeBuf().
Read()
int SCS::Read (u8 ID, u8 MemAddr, u8 * nData, u8 nLen)
References Error, INST_READ, readSCS(), rFlushSCS(), wFlushSCS(), and writeBuf().
Referenced by SCSCL::FeedBack(), SMS_STS::FeedBack(), SMSBL::FeedBack(), SMSCL::FeedBack(), readByte(), and readWord().
readByte()
int SCS::readByte (u8 ID, u8 MemAddr)
References Read().
Referenced by SCSCL::ReadMove(), SMS_STS::ReadMove(), SMSBL::ReadMove(), SMSCL::ReadMove(), SCSCL::ReadTemper(), SMS_STS::ReadTemper(), SMSBL::ReadTemper(), SMSCL::ReadTemper(), SCSCL::ReadVoltage(), SMS_STS::ReadVoltage(), SMSBL::ReadVoltage(), and SMSCL::ReadVoltage().
readSCS()
virtual int SCS::readSCS (unsigned char * nDat, int nLen) protected pure virtual
Implemented in SCSerial.
Referenced by Ack(), Ping(), Read(), and syncReadPacketTx().
readWord()
int SCS::readWord (u8 ID, u8 MemAddr)
References Read(), and SCS2Host().
Referenced by SCSCL::ReadCurrent(), SMS_STS::ReadCurrent(), SMSBL::ReadCurrent(), SMSCL::ReadCurrent(), SCSCL::ReadLoad(), SMS_STS::ReadLoad(), SMSBL::ReadLoad(), SMSCL::ReadLoad(), SCSCL::ReadPos(), SMS_STS::ReadPos(), SMSBL::ReadPos(), SMSCL::ReadPos(), SCSCL::ReadSpeed(), SMS_STS::ReadSpeed(), SMSBL::ReadSpeed(), and SMSCL::ReadSpeed().
regWrite()
int SCS::regWrite (u8 ID, u8 MemAddr, u8 * nDat, u8 nLen)
References Ack(), INST_REG_WRITE, rFlushSCS(), wFlushSCS(), and writeBuf().
Referenced by SCSCL::RegWritePos(), SMS_STS::RegWritePosEx(), SMSBL::RegWritePosEx(), SMSCL::RegWritePosEx(), SMS_STS::RegWritePwm(), and SMS_STS::RegWriteSpe().
RegWriteAction()
int SCS::RegWriteAction (u8 ID = 0xfe)
References Ack(), INST_REG_ACTION, rFlushSCS(), wFlushSCS(), and writeBuf().
rFlushSCS()
virtual void SCS::rFlushSCS () protected pure virtual
Implemented in SCSerial.
Referenced by genWrite(), Ping(), Read(), regWrite(), RegWriteAction(), syncReadPacketTx(), syncWrite(), writeByte(), and writeWord().
SCS2Host()
u16 SCS::SCS2Host (u8 DataL, u8 DataH) protected
References End.
Referenced by readWord(), and syncReadRxPacketToWrod().
syncReadBegin()
void SCS::syncReadBegin (u8 IDN, u8 rxLen)
References syncReadRxBuff, and syncReadRxBuffMax.
syncReadEnd()
void SCS::syncReadEnd ()
References syncReadRxBuff.
syncReadPacketRx()
int SCS::syncReadPacketRx (u8 ID, u8 * nDat)
References Error, syncReadRxBuff, syncReadRxBuffLen, syncReadRxPacket, syncReadRxPacketIndex, and syncReadRxPacketLen.
syncReadPacketTx()
int SCS::syncReadPacketTx (u8 ID[], u8 IDN, u8 MemAddr, u8 nLen)
References INST_SYNC_READ, readSCS(), rFlushSCS(), syncReadRxBuff, syncReadRxBuffLen, syncReadRxBuffMax, syncReadRxPacketLen, wFlushSCS(), and writeSCS().
syncReadRxPacketToByte()
int SCS::syncReadRxPacketToByte ()
References syncReadRxPacket, syncReadRxPacketIndex, and syncReadRxPacketLen.
syncReadRxPacketToWrod()
int SCS::syncReadRxPacketToWrod (u8 negBit = 0)
References SCS2Host(), syncReadRxPacket, syncReadRxPacketIndex, and syncReadRxPacketLen.
syncWrite()
void SCS::syncWrite (u8 ID[], u8 IDN, u8 MemAddr, u8 * nDat, u8 nLen)
References INST_SYNC_WRITE, rFlushSCS(), wFlushSCS(), and writeSCS().
Referenced by SCSCL::SyncWritePos(), SMS_STS::SyncWritePosEx(), SMSBL::SyncWritePosEx(), SMSCL::SyncWritePosEx(), SMS_STS::SyncWritePwm(), and SMS_STS::SyncWriteSpe().
wFlushSCS()
virtual void SCS::wFlushSCS () protected pure virtual
Implemented in SCSerial.
Referenced by genWrite(), Ping(), Read(), regWrite(), RegWriteAction(), syncReadPacketTx(), syncWrite(), writeByte(), and writeWord().
writeBuf()
void SCS::writeBuf (u8 ID, u8 MemAddr, u8 * nDat, u8 nLen, u8 Fun) protected
References writeSCS().
Referenced by genWrite(), Ping(), Read(), regWrite(), RegWriteAction(), writeByte(), and writeWord().
writeByte()
int SCS::writeByte (u8 ID, u8 MemAddr, u8 bDat)
References Ack(), INST_WRITE, rFlushSCS(), wFlushSCS(), and writeBuf().
Referenced by SMS_STS::CalibrationOfs(), SMSBL::CalibrationOfs(), SMSCL::CalibrationOfs(), SCSCL::EnableTorque(), SMS_STS::EnableTorque(), SMSBL::EnableTorque(), SMSCL::EnableTorque(), SCSCL::LockEprom(), SMS_STS::LockEprom(), SMSBL::LockEprom(), SMSCL::LockEprom(), SMS_STS::Mode(), SCSCL::unLockEprom(), SMS_STS::unLockEprom(), SMSBL::unLockEprom(), SMSCL::unLockEprom(), SMSBL::WheelMode(), and SMSCL::WheelMode().
writeSCS() [1/2]
virtual int SCS::writeSCS (unsigned char * nDat, int nLen) protected pure virtual
Implemented in SCSerial.
Referenced by syncReadPacketTx(), syncWrite(), and writeBuf().
writeSCS() [2/2]
virtual int SCS::writeSCS (unsigned char bDat) protected pure virtual
Implemented in SCSerial.
writeWord()
int SCS::writeWord (u8 ID, u8 MemAddr, u16 wDat)
References Ack(), Host2SCS(), INST_WRITE, rFlushSCS(), wFlushSCS(), and writeBuf().
Member Data Documentation
End
u8 SCS::End
Referenced by Host2SCS(), SCS(), SCS2Host(), SCSCL::SCSCL(), SMS_STS::SMS_STS(), SMSBL::SMSBL(), and SMSCL::SMSCL().
Error
u8 SCS::Error
Referenced by Ack(), Ping(), Read(), SCS(), and syncReadPacketRx().
Level
u8 SCS::Level
Referenced by Ack(), and SCS().
syncReadRxBuff
u8* SCS::syncReadRxBuff
Referenced by syncReadBegin(), syncReadEnd(), syncReadPacketRx(), and syncReadPacketTx().
syncReadRxBuffLen
u16 SCS::syncReadRxBuffLen
Referenced by syncReadPacketRx(), and syncReadPacketTx().
syncReadRxBuffMax
u16 SCS::syncReadRxBuffMax
Referenced by syncReadBegin(), and syncReadPacketTx().
syncReadRxPacket
u8* SCS::syncReadRxPacket
Referenced by syncReadPacketRx(), syncReadRxPacketToByte(), and syncReadRxPacketToWrod().
syncReadRxPacketIndex
u8 SCS::syncReadRxPacketIndex
Referenced by syncReadPacketRx(), syncReadRxPacketToByte(), and syncReadRxPacketToWrod().
syncReadRxPacketLen
u8 SCS::syncReadRxPacketLen
Referenced by syncReadPacketRx(), syncReadPacketTx(), syncReadRxPacketToByte(), and syncReadRxPacketToWrod().
The documentation for this class was generated from the following files:
scservo_sdk/SCS.h
scservo_sdk/SCS.cpp