SO101 Hardware Interface: SMSBL Class Reference
SMSBL Class Reference
#include <SMSBL.h>
Public Member Functions
SMSBL ()
SMSBL (u8 End)
SMSBL (u8 End, u8 Level)
virtual int WritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC=0)
virtual int RegWritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC=0)
virtual void SyncWritePosEx (u8 ID[], u8 IDN, s16 Position[], u16 Speed[], u8 ACC[])
virtual int WheelMode (u8 ID)
virtual int WriteSpe (u8 ID, s16 Speed, u8 ACC=0)
virtual int EnableTorque (u8 ID, u8 Enable)
virtual int unLockEprom (u8 ID)
virtual int LockEprom (u8 ID)
virtual int CalibrationOfs (u8 ID)
virtual int FeedBack (int ID)
virtual int ReadPos (int ID)
virtual int ReadSpeed (int ID)
virtual int ReadLoad (int ID)
virtual int ReadVoltage (int ID)
virtual int ReadTemper (int ID)
virtual int ReadMove (int ID)
virtual int ReadCurrent (int ID)
Public Member Functions inherited from SCSerial
SCSerial ()
SCSerial (u8 End)
SCSerial (u8 End, u8 Level)
virtual int getErr ()
virtual int setBaudRate (int baudRate)
virtual bool begin (int baudRate, const char *serialPort)
virtual void end ()
Public Member Functions inherited from SCS
SCS ()
SCS (u8 End)
SCS (u8 End, u8 Level)
int genWrite (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen)
int regWrite (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen)
int RegWriteAction (u8 ID=0xfe)
void syncWrite (u8 ID[], u8 IDN, u8 MemAddr, u8 *nDat, u8 nLen)
int writeByte (u8 ID, u8 MemAddr, u8 bDat)
int writeWord (u8 ID, u8 MemAddr, u16 wDat)
int Read (u8 ID, u8 MemAddr, u8 *nData, u8 nLen)
int readByte (u8 ID, u8 MemAddr)
int readWord (u8 ID, u8 MemAddr)
int Ping (u8 ID)
int syncReadPacketTx (u8 ID[], u8 IDN, u8 MemAddr, u8 nLen)
int syncReadPacketRx (u8 ID, u8 *nDat)
int syncReadRxPacketToByte ()
int syncReadRxPacketToWrod (u8 negBit=0)
void syncReadBegin (u8 IDN, u8 rxLen)
void syncReadEnd ()
Private Attributes
u8 Mem [SMSBL_PRESENT_CURRENT_H-SMSBL_PRESENT_POSITION_L+1]
Additional Inherited Members
Public Attributes inherited from SCSerial
unsigned long int IOTimeOut
int Err
Public Attributes inherited from SCS
u8 Level
u8 End
u8 Error
u8 syncReadRxPacketIndex
u8 syncReadRxPacketLen
u8 * syncReadRxPacket
u8 * syncReadRxBuff
u16 syncReadRxBuffLen
u16 syncReadRxBuffMax
Protected Member Functions inherited from SCSerial
int writeSCS (unsigned char *nDat, int nLen)
int readSCS (unsigned char *nDat, int nLen)
int writeSCS (unsigned char bDat)
void rFlushSCS ()
void wFlushSCS ()
Protected Member Functions inherited from SCS
void writeBuf (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen, u8 Fun)
void Host2SCS (u8 *DataL, u8 *DataH, u16 Data)
u16 SCS2Host (u8 DataL, u8 DataH)
int Ack (u8 ID)
Protected Attributes inherited from SCSerial
int fd
struct termios orgopt
struct termios curopt
unsigned char txBuf [255]
int txBufLen
Constructor & Destructor Documentation
SMSBL() [1/3]
SMSBL::SMSBL ()
References SCS::End.
SMSBL() [2/3]
SMSBL::SMSBL (u8 End)
SMSBL() [3/3]
SMSBL::SMSBL (u8 End, u8 Level)
Member Function Documentation
CalibrationOfs()
int SMSBL::CalibrationOfs (u8 ID) virtual
References SMSBL_TORQUE_ENABLE, and SCS::writeByte().
EnableTorque()
int SMSBL::EnableTorque (u8 ID, u8 Enable) virtual
References SMSBL_TORQUE_ENABLE, and SCS::writeByte().
FeedBack()
int SMSBL::FeedBack (int ID) virtual
References SCSerial::Err, Mem, SCS::Read(), and SMSBL_PRESENT_POSITION_L.
LockEprom()
int SMSBL::LockEprom (u8 ID) virtual
References SMSBL_LOCK, and SCS::writeByte().
ReadCurrent()
int SMSBL::ReadCurrent (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMSBL_PRESENT_CURRENT_H, SMSBL_PRESENT_CURRENT_L, and SMSBL_PRESENT_POSITION_L.
ReadLoad()
int SMSBL::ReadLoad (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMSBL_PRESENT_LOAD_H, SMSBL_PRESENT_LOAD_L, and SMSBL_PRESENT_POSITION_L.
ReadMove()
int SMSBL::ReadMove (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SMSBL_MOVING, and SMSBL_PRESENT_POSITION_L.
ReadPos()
int SMSBL::ReadPos (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMSBL_PRESENT_POSITION_H, and SMSBL_PRESENT_POSITION_L.
ReadSpeed()
int SMSBL::ReadSpeed (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMSBL_PRESENT_POSITION_L, SMSBL_PRESENT_SPEED_H, and SMSBL_PRESENT_SPEED_L.
ReadTemper()
int SMSBL::ReadTemper (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SMSBL_PRESENT_POSITION_L, and SMSBL_PRESENT_TEMPERATURE.
ReadVoltage()
int SMSBL::ReadVoltage (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SMSBL_PRESENT_POSITION_L, and SMSBL_PRESENT_VOLTAGE.
RegWritePosEx()
int SMSBL::RegWritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC = 0) virtual
References SCS::Host2SCS(), SCS::regWrite(), and SMSBL_ACC.
SyncWritePosEx()
void SMSBL::SyncWritePosEx (u8 ID[], u8 IDN, s16 Position[], u16 Speed[], u8 ACC[]) virtual
References SCS::Host2SCS(), SMSBL_ACC, and SCS::syncWrite().
unLockEprom()
int SMSBL::unLockEprom (u8 ID) virtual
References SMSBL_LOCK, and SCS::writeByte().
WheelMode()
int SMSBL::WheelMode (u8 ID) virtual
References SMSBL_MODE, and SCS::writeByte().
WritePosEx()
int SMSBL::WritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC = 0) virtual
References SCS::genWrite(), SCS::Host2SCS(), and SMSBL_ACC.
WriteSpe()
int SMSBL::WriteSpe (u8 ID, s16 Speed, u8 ACC = 0) virtual
References SCS::genWrite(), SCS::Host2SCS(), SMSBL_ACC, and SMSBL_GOAL_SPEED_L.
Member Data Documentation
Mem
u8 SMSBL::Mem[SMSBL_PRESENT_CURRENT_H-SMSBL_PRESENT_POSITION_L+1] private
Referenced by FeedBack(), ReadCurrent(), ReadLoad(), ReadMove(), ReadPos(), ReadSpeed(), ReadTemper(), and ReadVoltage().
The documentation for this class was generated from the following files:
scservo_sdk/SMSBL.h
scservo_sdk/SMSBL.cpp