SO101 Hardware Interface: SMSCL Class Reference
SMSCL Class Reference
#include <SMSCL.h>
Public Member Functions
SMSCL ()
SMSCL (u8 End)
SMSCL (u8 End, u8 Level)
virtual int WritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC=0)
virtual int RegWritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC=0)
virtual void SyncWritePosEx (u8 ID[], u8 IDN, s16 Position[], u16 Speed[], u8 ACC[])
virtual int WheelMode (u8 ID)
virtual int WriteSpe (u8 ID, s16 Speed, u8 ACC=0)
virtual int EnableTorque (u8 ID, u8 Enable)
virtual int unLockEprom (u8 ID)
virtual int LockEprom (u8 ID)
virtual int CalibrationOfs (u8 ID)
virtual int FeedBack (int ID)
virtual int ReadPos (int ID)
virtual int ReadSpeed (int ID)
virtual int ReadLoad (int ID)
virtual int ReadVoltage (int ID)
virtual int ReadTemper (int ID)
virtual int ReadMove (int ID)
virtual int ReadCurrent (int ID)
Public Member Functions inherited from SCSerial
SCSerial ()
SCSerial (u8 End)
SCSerial (u8 End, u8 Level)
virtual int getErr ()
virtual int setBaudRate (int baudRate)
virtual bool begin (int baudRate, const char *serialPort)
virtual void end ()
Public Member Functions inherited from SCS
SCS ()
SCS (u8 End)
SCS (u8 End, u8 Level)
int genWrite (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen)
int regWrite (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen)
int RegWriteAction (u8 ID=0xfe)
void syncWrite (u8 ID[], u8 IDN, u8 MemAddr, u8 *nDat, u8 nLen)
int writeByte (u8 ID, u8 MemAddr, u8 bDat)
int writeWord (u8 ID, u8 MemAddr, u16 wDat)
int Read (u8 ID, u8 MemAddr, u8 *nData, u8 nLen)
int readByte (u8 ID, u8 MemAddr)
int readWord (u8 ID, u8 MemAddr)
int Ping (u8 ID)
int syncReadPacketTx (u8 ID[], u8 IDN, u8 MemAddr, u8 nLen)
int syncReadPacketRx (u8 ID, u8 *nDat)
int syncReadRxPacketToByte ()
int syncReadRxPacketToWrod (u8 negBit=0)
void syncReadBegin (u8 IDN, u8 rxLen)
void syncReadEnd ()
Private Attributes
u8 Mem [SMSCL_PRESENT_CURRENT_H-SMSCL_PRESENT_POSITION_L+1]
Additional Inherited Members
Public Attributes inherited from SCSerial
unsigned long int IOTimeOut
int Err
Public Attributes inherited from SCS
u8 Level
u8 End
u8 Error
u8 syncReadRxPacketIndex
u8 syncReadRxPacketLen
u8 * syncReadRxPacket
u8 * syncReadRxBuff
u16 syncReadRxBuffLen
u16 syncReadRxBuffMax
Protected Member Functions inherited from SCSerial
int writeSCS (unsigned char *nDat, int nLen)
int readSCS (unsigned char *nDat, int nLen)
int writeSCS (unsigned char bDat)
void rFlushSCS ()
void wFlushSCS ()
Protected Member Functions inherited from SCS
void writeBuf (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen, u8 Fun)
void Host2SCS (u8 *DataL, u8 *DataH, u16 Data)
u16 SCS2Host (u8 DataL, u8 DataH)
int Ack (u8 ID)
Protected Attributes inherited from SCSerial
int fd
struct termios orgopt
struct termios curopt
unsigned char txBuf [255]
int txBufLen
Constructor & Destructor Documentation
SMSCL() [1/3]
SMSCL::SMSCL ()
References SCS::End.
SMSCL() [2/3]
SMSCL::SMSCL (u8 End)
SMSCL() [3/3]
SMSCL::SMSCL (u8 End, u8 Level)
Member Function Documentation
CalibrationOfs()
int SMSCL::CalibrationOfs (u8 ID) virtual
References SMSCL_TORQUE_ENABLE, and SCS::writeByte().
EnableTorque()
int SMSCL::EnableTorque (u8 ID, u8 Enable) virtual
References SMSCL_TORQUE_ENABLE, and SCS::writeByte().
FeedBack()
int SMSCL::FeedBack (int ID) virtual
References SCSerial::Err, Mem, SCS::Read(), and SMSCL_PRESENT_POSITION_L.
LockEprom()
int SMSCL::LockEprom (u8 ID) virtual
References SMSCL_LOCK, and SCS::writeByte().
ReadCurrent()
int SMSCL::ReadCurrent (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMSCL_PRESENT_CURRENT_H, SMSCL_PRESENT_CURRENT_L, and SMSCL_PRESENT_POSITION_L.
ReadLoad()
int SMSCL::ReadLoad (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMSCL_PRESENT_LOAD_H, SMSCL_PRESENT_LOAD_L, and SMSCL_PRESENT_POSITION_L.
ReadMove()
int SMSCL::ReadMove (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SMSCL_MOVING, and SMSCL_PRESENT_POSITION_L.
ReadPos()
int SMSCL::ReadPos (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMSCL_PRESENT_POSITION_H, and SMSCL_PRESENT_POSITION_L.
ReadSpeed()
int SMSCL::ReadSpeed (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SMSCL_PRESENT_POSITION_L, SMSCL_PRESENT_SPEED_H, and SMSCL_PRESENT_SPEED_L.
ReadTemper()
int SMSCL::ReadTemper (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SMSCL_PRESENT_POSITION_L, and SMSCL_PRESENT_TEMPERATURE.
ReadVoltage()
int SMSCL::ReadVoltage (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SMSCL_PRESENT_POSITION_L, and SMSCL_PRESENT_VOLTAGE.
RegWritePosEx()
int SMSCL::RegWritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC = 0) virtual
References SCS::Host2SCS(), SCS::regWrite(), and SMSCL_ACC.
SyncWritePosEx()
void SMSCL::SyncWritePosEx (u8 ID[], u8 IDN, s16 Position[], u16 Speed[], u8 ACC[]) virtual
References SCS::Host2SCS(), SMSCL_ACC, and SCS::syncWrite().
unLockEprom()
int SMSCL::unLockEprom (u8 ID) virtual
References SMSCL_LOCK, and SCS::writeByte().
WheelMode()
int SMSCL::WheelMode (u8 ID) virtual
References SMSCL_MODE, and SCS::writeByte().
WritePosEx()
int SMSCL::WritePosEx (u8 ID, s16 Position, u16 Speed, u8 ACC = 0) virtual
References SCS::genWrite(), SCS::Host2SCS(), and SMSCL_ACC.
WriteSpe()
int SMSCL::WriteSpe (u8 ID, s16 Speed, u8 ACC = 0) virtual
References SCS::genWrite(), SCS::Host2SCS(), SMSCL_ACC, and SMSCL_GOAL_SPEED_L.
Member Data Documentation
Mem
u8 SMSCL::Mem[SMSCL_PRESENT_CURRENT_H-SMSCL_PRESENT_POSITION_L+1] private
Referenced by FeedBack(), ReadCurrent(), ReadLoad(), ReadMove(), ReadPos(), ReadSpeed(), ReadTemper(), and ReadVoltage().
The documentation for this class was generated from the following files:
scservo_sdk/SMSCL.h
scservo_sdk/SMSCL.cpp