SO101 Hardware Interface: SCSCL Class Reference
SCSCL Class Reference
#include <SCSCL.h>
Public Member Functions
SCSCL ()
SCSCL (u8 End)
SCSCL (u8 End, u8 Level)
virtual int WritePos (u8 ID, u16 Position, u16 Time, u16 Speed=0)
virtual int RegWritePos (u8 ID, u16 Position, u16 Time, u16 Speed=0)
virtual void SyncWritePos (u8 ID[], u8 IDN, u16 Position[], u16 Time[], u16 Speed[])
virtual int PWMMode (u8 ID)
virtual int WritePWM (u8 ID, s16 pwmOut)
virtual int EnableTorque (u8 ID, u8 Enable)
virtual int unLockEprom (u8 ID)
virtual int LockEprom (u8 ID)
virtual int FeedBack (int ID)
virtual int ReadPos (int ID)
virtual int ReadSpeed (int ID)
virtual int ReadLoad (int ID)
virtual int ReadVoltage (int ID)
virtual int ReadTemper (int ID)
virtual int ReadMove (int ID)
virtual int ReadCurrent (int ID)
Public Member Functions inherited from SCSerial
SCSerial ()
SCSerial (u8 End)
SCSerial (u8 End, u8 Level)
virtual int getErr ()
virtual int setBaudRate (int baudRate)
virtual bool begin (int baudRate, const char *serialPort)
virtual void end ()
Public Member Functions inherited from SCS
SCS ()
SCS (u8 End)
SCS (u8 End, u8 Level)
int genWrite (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen)
int regWrite (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen)
int RegWriteAction (u8 ID=0xfe)
void syncWrite (u8 ID[], u8 IDN, u8 MemAddr, u8 *nDat, u8 nLen)
int writeByte (u8 ID, u8 MemAddr, u8 bDat)
int writeWord (u8 ID, u8 MemAddr, u16 wDat)
int Read (u8 ID, u8 MemAddr, u8 *nData, u8 nLen)
int readByte (u8 ID, u8 MemAddr)
int readWord (u8 ID, u8 MemAddr)
int Ping (u8 ID)
int syncReadPacketTx (u8 ID[], u8 IDN, u8 MemAddr, u8 nLen)
int syncReadPacketRx (u8 ID, u8 *nDat)
int syncReadRxPacketToByte ()
int syncReadRxPacketToWrod (u8 negBit=0)
void syncReadBegin (u8 IDN, u8 rxLen)
void syncReadEnd ()
Private Attributes
u8 Mem [SCSCL_PRESENT_CURRENT_H-SCSCL_PRESENT_POSITION_L+1]
Additional Inherited Members
Public Attributes inherited from SCSerial
unsigned long int IOTimeOut
int Err
Public Attributes inherited from SCS
u8 Level
u8 End
u8 Error
u8 syncReadRxPacketIndex
u8 syncReadRxPacketLen
u8 * syncReadRxPacket
u8 * syncReadRxBuff
u16 syncReadRxBuffLen
u16 syncReadRxBuffMax
Protected Member Functions inherited from SCSerial
int writeSCS (unsigned char *nDat, int nLen)
int readSCS (unsigned char *nDat, int nLen)
int writeSCS (unsigned char bDat)
void rFlushSCS ()
void wFlushSCS ()
Protected Member Functions inherited from SCS
void writeBuf (u8 ID, u8 MemAddr, u8 *nDat, u8 nLen, u8 Fun)
void Host2SCS (u8 *DataL, u8 *DataH, u16 Data)
u16 SCS2Host (u8 DataL, u8 DataH)
int Ack (u8 ID)
Protected Attributes inherited from SCSerial
int fd
struct termios orgopt
struct termios curopt
unsigned char txBuf [255]
int txBufLen
Constructor & Destructor Documentation
SCSCL() [1/3]
SCSCL::SCSCL ()
References SCS::End.
SCSCL() [2/3]
SCSCL::SCSCL (u8 End)
SCSCL() [3/3]
SCSCL::SCSCL (u8 End, u8 Level)
Member Function Documentation
EnableTorque()
int SCSCL::EnableTorque (u8 ID, u8 Enable) virtual
References SCSCL_TORQUE_ENABLE, and SCS::writeByte().
FeedBack()
int SCSCL::FeedBack (int ID) virtual
References SCSerial::Err, Mem, SCS::Read(), and SCSCL_PRESENT_POSITION_L.
LockEprom()
int SCSCL::LockEprom (u8 ID) virtual
References SCSCL_LOCK, and SCS::writeByte().
PWMMode()
int SCSCL::PWMMode (u8 ID) virtual
References SCS::genWrite(), and SCSCL_MIN_ANGLE_LIMIT_L.
ReadCurrent()
int SCSCL::ReadCurrent (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SCSCL_PRESENT_CURRENT_H, SCSCL_PRESENT_CURRENT_L, and SCSCL_PRESENT_POSITION_L.
ReadLoad()
int SCSCL::ReadLoad (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SCSCL_PRESENT_LOAD_H, SCSCL_PRESENT_LOAD_L, and SCSCL_PRESENT_POSITION_L.
ReadMove()
int SCSCL::ReadMove (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SCSCL_MOVING, and SCSCL_PRESENT_POSITION_L.
ReadPos()
int SCSCL::ReadPos (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SCSCL_PRESENT_POSITION_H, and SCSCL_PRESENT_POSITION_L.
ReadSpeed()
int SCSCL::ReadSpeed (int ID) virtual
References SCSerial::Err, Mem, SCS::readWord(), SCSCL_PRESENT_POSITION_L, SCSCL_PRESENT_SPEED_H, and SCSCL_PRESENT_SPEED_L.
ReadTemper()
int SCSCL::ReadTemper (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SCSCL_PRESENT_POSITION_L, and SCSCL_PRESENT_TEMPERATURE.
ReadVoltage()
int SCSCL::ReadVoltage (int ID) virtual
References SCSerial::Err, Mem, SCS::readByte(), SCSCL_PRESENT_POSITION_L, and SCSCL_PRESENT_VOLTAGE.
RegWritePos()
int SCSCL::RegWritePos (u8 ID, u16 Position, u16 Time, u16 Speed = 0) virtual
References SCS::Host2SCS(), SCS::regWrite(), and SCSCL_GOAL_POSITION_L.
SyncWritePos()
void SCSCL::SyncWritePos (u8 ID[], u8 IDN, u16 Position[], u16 Time[], u16 Speed[]) virtual
References SCS::Host2SCS(), SCSCL_GOAL_POSITION_L, and SCS::syncWrite().
unLockEprom()
int SCSCL::unLockEprom (u8 ID) virtual
References SCSCL_LOCK, and SCS::writeByte().
WritePos()
int SCSCL::WritePos (u8 ID, u16 Position, u16 Time, u16 Speed = 0) virtual
References SCS::genWrite(), SCS::Host2SCS(), and SCSCL_GOAL_POSITION_L.
WritePWM()
int SCSCL::WritePWM (u8 ID, s16 pwmOut) virtual
References SCS::genWrite(), SCS::Host2SCS(), and SCSCL_GOAL_TIME_L.
Member Data Documentation
Mem
u8 SCSCL::Mem[SCSCL_PRESENT_CURRENT_H-SCSCL_PRESENT_POSITION_L+1] private
Referenced by FeedBack(), ReadCurrent(), ReadLoad(), ReadMove(), ReadPos(), ReadSpeed(), ReadTemper(), and ReadVoltage().
The documentation for this class was generated from the following files:
scservo_sdk/SCSCL.h
scservo_sdk/SCSCL.cpp